### PR TITLE
Create Incentivizing Participation Nodes Via xGov Rewards.

### PR DESCRIPTION
**Pull request by GhostOfMcAfee**

### CODE REVIEW

**Review by fifthrace — COMMENTED** [review]
This seems like a good proposal imo. The barrier to entry is low.

**Comment by Derova** [comment]
I'm onboard with this.

**Comment by GhostOfMcAfee** [comment]
I'm going to start working on a more serious and well put together proposal. I'm just commenting here to keep the GitHub bot from killing it before it can be merged into something else.

**Comment by GhostOfMcAfee** [comment]
closing this pull request. I am going to start working on something more formal to deal with this.

**Pull request closed without merging**
