### PR TITLE
ARC for standardizing traits (attributes) in token metadata

### PR DESCRIPTION
**Pull request by keeganthomp**
Establishes a standard for how to declare an NFT's traits inside a token's metadata.

### CODE REVIEW

**Comment by whereisrysmind** [comment]
+1

**Comment by koen-vr** [comment]
ATM this would be valid, and further nesting as well? If that is the goal, it should be more explicit?

```json
{
  ...
  "properties": {
    "creator": "Tim Smith",
    "created_at": "January 2, 2022",
    "traits": {
      "background": "red",
      "shirt_color": "blue",
      "glasses": {
        "style": 5,
        "color": "green"
      },
      "tattoos": [
        4, 2, 8
      ],
    }
  }
}
```

**Comment by keeganthomp** [comment]
No, that would not be valid according to this spec.

"Values must be strings or numbers".

My goal is to propose a simple solution that is easily digestible by programs. Once you allow nesting, it's a slippery slope that will inevitably lead a pile of spaghetti.

The people seemed to really like the unofficial ARC69. This is narrowed heavily from that and inspired from ARC3.

**Comment by koen-vr** [comment]
> No, that would not be valid according to this spec.
>
> "Values must be strings or numbers".

Ok, I was not clear about your intent, Then on line 49 I would change 'may' to "must" to be in line with [RFC-2119](https://www.ietf.org/rfc/rfc2119.txt). Then repeat the rule outside of the description or add validation rules to the schema so the following the schema enforces the rule.

```json
{
  "title": "Traits for Non-Fungible Token",
  "type": "object",
  "properties": {
    "traits": {
      "type": "object",
      "description": "Traits (attributes) that can be used to calculate things like rarity. Values must be strings or numbers",
      "minProperties": 1,
      "additionalProperties": {
        "type": ["number", "string"],
      }
    }
  }
}
```

**Comment by fabrice102** [comment]
There seems to be some consensus there.
So merging it in the main repo and creating an issue for discussion:
Discussion is now on https://github.com/algorandfoundation/ARCs/issues/62

**Comment by jannotti** [comment]
I'm concerned about using "none" as a special value.  Why not use `null`, an existing JSON value?

**Pull request merged**
