### PR TITLE
ARC-48 Improving flexibility 

### PR DESCRIPTION
**Pull request by SudoWeezy**
Improving the Measure (ARC48) to propose for the community to allow more flexibility on DEFI priorities. 
The projects would then be able to reward users and work on user acquisition. 

It is an improvement to reduce admin burden and economically insignificant (smaller) reward amounts. And, all rewards utilisation will be disclosed to the community in whole (publicly and timely) and, wholly devoted to protocol provision, user rewards, user engagement.

### CODE REVIEW

**Comment by nonfungibleab** [comment]
The DeFi committee is proposing that in the Rewards Distribution the text would be changed from:

_Rewards under this program will be distributed to projects within 4 weeks of the scheduled start date of the new governance period and the project(s) must distribute the totality of the amount received as incentives to their users, with at least 95% of rewards distributed by the end of the period and the remainder distributed in the following period. The methodology for payment must be made public and approved by the Algorand DeFi advisory committee prior to distribution._

To:

_Rewards under this program will be distributed to projects within 4 weeks of the scheduled start date of the new governance period and the project(s). The usage of these rewards will be made public, and they will be entirely dedicated to protocol provision, user rewards, and user engagement. The use of rewards and methodology for payment must be made public and approved by the Algorand DeFi advisory committee prior to distribution._


IMV, it's a good initial draft, but the committee should define the activities would fall on each of the categories - protocol provision, user rewards and user engagement - and the most percentage of rewards that would be allocate to each. For example, 80% for user rewards, 10% for user engagement and 10% for protocol provision, OR 70/20/10.

**Comment by ErikHasselwander** [comment]
I strongly dislike the idea of having **Targeted DeFi rewards** go towards "user engagement". This is not what Decentralized Finance is about, because user engagement will probably be things that are not DeFi, like off-chain competitions and stuff. What was voted for in general governance was for all the money to go to DeFi rewards, and now we're suddenly thinking that only having 70% go to rewards is OK. To me this requires a new general governance vote.

How would something like "protocol provision" work? Does that liquidity have to be inside the protocol forever, or just for the period which the projects after can either claim them themselves or do they have to distribute them?

I can see why more flexibility is something projects is asking for, but I do not think this flexibility should allow things that are not DeFi or rewards (user engagement/liquidity provision) to happen, especially not with a third of the entire pot. The APRs that projects are able to provide right now should be able to market themselves, or projects can apply for xgov grants for user engagement budgets.

**Comment by ErikHasselwander** [comment]
Are any individual projects able to post any increase in users/engagement/followers/whatever for this past period of TDR, where I think there has been a trial run of allowing some of the ALGOs to go towards engagement/marketing. I am not seeing it and I think that whoever is asking for this should be able to demonstrate some kind of effectiveness.

**Comment by defichamp** [comment]
80%  User rewards, 10% for user engagement and 10% for protocol provision seems like a good balance. There is certainly a need for protocols to have some flexibility in their reward spends, user acquisition should be a top priority for all in the community especially after we lost so many post myalgo. I believe all spending should be made public, perhaps we could run this for 2 periods and see what protocols have managed to do. Would there be any assistance from the foundation with regards to access to influencers and marketing?

**Comment by BunsanMuchi** [comment]
They already were alloted up to 5% this period for marketing iirc. So far we personally have not seen a user uptick and I don't see any engagement metrics nor KPIs being disclosed by any project. This lack of accountability from the DeFi protocols makes me wary of laxing the ARC. Ofc there's always time to change, but I've yet to see one report of rewards given, on what format and how it went with respects to the marketing push. And I'm an active member of the space, I think the only thing I've tracked down was the algos spent on consensus by FF.

**Comment by GilesTNT** [comment]
> They already were alloted up to 5% this period for marketing iirc. So far we personally have not seen a user uptick and I don't see any engagement metrics nor KPIs being disclosed by any project. This lack of accountability from the DeFi protocols makes me wary of laxing the ARC. Ofc there's always time to change, but I've yet to see one report of rewards given, on what format and how it went with respects to the marketing push. And I'm an active member of the space, I think the only thing I've tracked down was the algos spent on consensus by FF.

I think you need to wait until the end of the period before you see any metrics. It's a bit harsh to throw lack of accountability around before we complete.  Many of us have small teams and overly demanding reporting takes up precious time. Algomint have certainly seen an uptick in their native token price and volume this period along with increased engagement and we certainly aim to be transparent and share metrics once this period closes.

**Comment by GilesTNT** [comment]
Also From a protocol point of view it's essential we have some flexibility with regard to reward spends given the current environment we all need a little help to survive and user acquisition is vital. I agree with @ErikHasselwander that spending should be disclosed and this can be achieved without it being overly burdensome.  Algomint recently created X-NFT, a protocol that enables users to either mint nft's or hold the X-NFT token and be exposed to a portfolio of art. This was partially funded by the 5% rewards and has provided considerable growth in both volume and value of the Algomint token "goMINT". We have also seen greater engagement across our social media channels (particularly X) and have seen some small engagement beyond the Algorand ecosystem.

**Comment by 2lobo** [comment]
Problem is the dapps don't communicate their rewards structure in advance that publicly aside from FF who posted it in their forum. but even then it just says 10% for marketing which isnt really helpful. So I don't even know what percentage other protocols use for farming and user engagement.

On top I want to know if their user engagement ideas actually work, I want some numbers. Not really convinced in the stuff I saw from protocols untill now. It feels also like power users who farm the defi boost anyways (already a good return) are the ones profiting even more by some of the user engagement ideas which seems wrong as it should be about getting new users in. I mean I take the free ALGOs but if its that easily gameable like the xALGO rewards by FF its not really worth helpful for the ecosystem imho




> Also From a protocol point of view it's essential we have some flexibility with regard to reward spends given the current environment we all need a little help to survive and user acquisition is vital. I agree with @ErikHasselwander that spending should be disclosed and this can be achieved without it being overly burdensome. Algomint recently created X-NFT, a protocol that enables users to either mint nft's or hold the X-NFT token and be exposed to a portfolio of art. This was partially funded by the 5% rewards and has provided considerable growth in both volume and value of the Algomint token "goMINT". We have also seen greater engagement across our social media channels (particularly X) and have seen some small engagement beyond the Algorand ecosystem.

You added nice gamification to Defi through X-NFT but lets be honest if you give me a decent amount of ALGOs I can pump any token (if it isnt already one of the tokens with high liquidity). Also what value does it really add to the ecosystem if you pump a token through rewards funded by the defi boost? Doesnt sound like a good long term solution

**Comment by GilesTNT** [comment]
@2lobo 
I recommend reading the medium article here https://algomint.medium.com/x-nft-4d4153096f35 the programme is designed to be long term and we are working on bringing a range of different artists to contribute to the portfolio (some more mainstream than others). 

We are currently in a situation where rewards just go round and round within our small community, which is great if you only care about getting as much yield as you can in a battered and contracted environment, however protocols can't survive by simply circulating rewards. The unfortunate truth is we need help to market our products, create innovative platforms and try to reach out to the broader crypto community. I 100% agree with transparency of spends, being accountable for our use of funds but to stymie our ability to grow communities and innovate by shutting down a potential life line is counterintuitive. The foundation have recognised the defi ecosystem needs a little support and flexibility and this seems like a reasonable approach.

**Comment by ErikHasselwander** [comment]
Speaking of the effect of this program, pact.fi did a giveaway of 50k ALGO for "Swapping, Liking, Following and tagging". This was given **to a single user** (https://algoexplorer.io/tx/MAIIV33CDXFPTWOSFCSLLD43VDGCZWCOS5TAR7S5HPMNMPZOV7HA), with no way of verification of the winner/how it was done. I strongly disagree that this is what defi protocols need to succeed. And to add salt to the wound those 50k ALGOs were instantly dumped and withdrawn to binance (https://algoexplorer.io/tx/YXJVUEM57IKRSHFUUISR2W6JJF2UHRARXKK2X6IR2QBIK37WQ5OA). I do not think this is appropriate use of the targeted defi rewards, and I do not think this is a way of marketing that will give any kind of ROR for the community, the chain or the individual projects. We do not need to give projects money for this kind of thing, because it is obviously not working. 

We need checks and balances and concrete plans. We can't just throw "flexible money" at the teams which just ends up being dumped on the market by people who are not even active on here. Once the people who are pushing for this can demonstrate a clear marketing plan that will actually generate new users etc I am all for *a general vote for a marketing budget*, but right now it's completely centralized with no checks. This is insanity to me, especially since we're all in the DeFi market. This is as far away as you can get from DeFi imo.

**Comment by 2lobo** [comment]
something like that is the problem and why its not a easy as: give the dapps some freedom because they need it to get new users. that feels more like wasting ALGOs

**Comment by 2lobo** [comment]
> @2lobo I recommend reading the medium article here https://algomint.medium.com/x-nft-4d4153096f35 the programme is designed to be long term and we are working on bringing a range of different artists to contribute to the portfolio (some more mainstream than others).
> 
> We are currently in a situation where rewards just go round and round within our small community, which is great if you only care about getting as much yield as you can in a battered and contracted environment, however protocols can't survive by simply circulating rewards. The unfortunate truth is we need help to market our products, create innovative platforms and try to reach out to the broader crypto community. I 100% agree with transparency of spends, being accountable for our use of funds but to stymie our ability to grow communities and innovate by shutting down a potential life line is counterintuitive. The foundation have recognised the defi ecosystem needs a little support and flexibility and this seems like a reasonable approach.

can you clarify where part of the defi boost was used for X-NFT? Just as farming rewards? Because that would be kinda normal

**Comment by ShaperOfEntropy** [comment]
> I do not think this is appropriate use of the targeted defi rewards.
> We need checks and balances and concrete plans.

Completely agree.

[The winner](https://algoexplorer.io/address/A53YVYWHV5RN72FTLP5W5BLRESU6JIQTOWR3DHI5CQ5LWOSO6OP75TSI2M) of the Pact.fi 50k giveaway seeded its account 4 days before the giveaway was announced.
It remained inactive until the giveaway started and then made exactly two swaps on Pact.fi for a total of 30 ALGO.
Then it remained again inactive until it received the reward and sold it for USDC and transfered it to Binance via Binance's [hot wallet](https://algoexplorer.io/address/AVQZHHNLFBOG7XBNOWCN3KKQYUKI2NO5EYHETLGZ5BBT4HE73K7ZYYDOBI).
The same Binance's hot wallet received multiple times in the past amounts above 5k USDC from [choppa.algo](https://algoexplorer.io/address/WQFL4RWPTTWA5GP2RFBTKYQDW5F3AFXGLVESQUQMAZPPPPCZQS5ECM74BE) or [another account](https://algoexplorer.io/address/DB74BLKUOYBXE4AACA4VYGUQA232B6RVMSQH3Z6YLZHIKYKOQIMJT7YYOI) that was seeded by choppa.algo.
[Choppa](https://twitter.com/CHOPPAtheSHARK) is one of the core members of Pact.fi.
[He announced in Discord](https://discord.com/channels/902378441473662987/942956907608563772/983587705390776372) that he secured the choppa.algo and posted it multiple times on Twitter, e.g. [here](https://twitter.com/CHOPPAtheSHARK/status/1567073914622464001).
The winner's [Twitter account @BVandl](https://twitter.com/BVandl) indicates the user is Australian.
Pact.fi's team is Australian.

This is just one too many coincidence for my taste, without the ability to verify the randomness of the result.

Therefore, I suggest to add a requirement to T&C of DeFi rewards that any giveaway must be verifiably random.
For example of such a Twitter giveaway, after the deadline to enter passes, the project must announce the list of eligible participants and a future round number in which the draw of the winner will be made.
A hash of the list and the round number is made and e.g. sent in a note field to the project distribution wallet.
The on-chain randomness beacon is used to get the random draw at the committed round number.

**Comment by 2lobo** [comment]
> > I do not think this is appropriate use of the targeted defi rewards.
> > We need checks and balances and concrete plans.
> 
> Completely agree.
> 
> [The winner](https://algoexplorer.io/address/A53YVYWHV5RN72FTLP5W5BLRESU6JIQTOWR3DHI5CQ5LWOSO6OP75TSI2M) of the Pact.fi 50k giveaway seeded its account 4 days before the giveaway was announced. It remained inactive until the giveaway started and then made exactly two swaps on Pact.fi for a total of 30 ALGO. Then it remained again inactive until it received the reward and sold it for USDC and transfered it to Binance via Binance's [hot wallet](https://algoexplorer.io/address/AVQZHHNLFBOG7XBNOWCN3KKQYUKI2NO5EYHETLGZ5BBT4HE73K7ZYYDOBI). The same Binance's hot wallet received multiple times in the past amounts above 5k USDC from [choppa.algo](https://algoexplorer.io/address/WQFL4RWPTTWA5GP2RFBTKYQDW5F3AFXGLVESQUQMAZPPPPCZQS5ECM74BE) or [another account](https://algoexplorer.io/address/DB74BLKUOYBXE4AACA4VYGUQA232B6RVMSQH3Z6YLZHIKYKOQIMJT7YYOI) that was seeded by choppa.algo. [Choppa](https://twitter.com/CHOPPAtheSHARK) is one of the core members of Pact.fi. [He announced in Discord](https://discord.com/channels/902378441473662987/942956907608563772/983587705390776372) that he secured the choppa.algo and posted it multiple times on Twitter, e.g. [here](https://twitter.com/CHOPPAtheSHARK/status/1567073914622464001). The winner's [Twitter account @BVandl](https://twitter.com/BVandl) indicates the user is Australian. Pact.fi's team is Australian.
> 
> This is just one too many coincidence for my taste, without the ability to verify the randomness of the result.
> 
> Therefore, I suggest to add a requirement to T&C of DeFi rewards that any giveaway must be verifiably random. For example of such a Twitter giveaway, after the deadline to enter passes, the project must announce the list of eligible participants and a future round number in which the draw of the winner will be made. A hash of the list and the round number is made and e.g. sent in a note field to the project distribution wallet. The on-chain randomness beacon is used to get the random draw at the committed round number.

just to say it: i dont think at all that it got rigged by anyone over at pact, they are a great team!

but the conclusion that ALGOs given out this way must be verifiably random is good imo

**Comment by GilesTNT** [comment]
@2lobo as previously mentioned, all spending of rewards will be detailed at the end of the period. I can say that 8000A were allocated to deployment costs (minting on chain) the remainder will be split across the NFT design and contract development. Keep in mind ALL X-NFT tokens are earnt by providing liquidity, and a small number will be made available to drive more social engagement. All the details will be posted (as I mentioned earlier) in our end of period reporting. I would also like to add we have created a longterm product and added huge value with a small spend. We really want to engage the artists pool beyond Algorand and continued support for this programme would go a long way to help us reach that goal. A number of folk in our team/ecosystem have given up a huge amount of time to get this off the ground and see the long term vision. Also I would like to add that in the case of giveaways verifiably random is key to trust and 100% agree it should be applied.

**Comment by ErikHasselwander** [comment]
> the remainder will be split across the NFT design and contract development

Am I getting this right, are you guys already spending your Targeted Defi Rewards budget for *contract development*? Marketing is one thing, but using it to develop is just taking the money for yourselves. @GilesTNT

**Comment by 2lobo** [comment]
> @2lobo as previously mentioned, all spending of rewards will be detailed at the end of the period. I can say that 8000A were allocated to deployment costs (minting on chain) the remainder will be split across the NFT design and contract development. Keep in mind ALL X-NFT tokens are earnt by providing liquidity, and a small number will be made available to drive more social engagement. All the details will be posted (as I mentioned earlier) in our end of period reporting. I would also like to add we have created a longterm product and added huge value with a small spend. We really want to engage the artists pool beyond Algorand and continued support for this programme would go a long way to help us reach that goal. A number of folk in our team/ecosystem have given up a huge amount of time to get this off the ground and see the long term vision. Also I would like to add that in the case of giveaways verifiably random is key to trust and 100% agree it should be applied.

the thing is just because its a good idea you cant justify misusing funds with it. i honestly like X-NFT brings fun and excitement to defi and could help onboarding NFT users to defi. but misusing funds is still musing funds and i honestly dont care what you would present as evidence after the period about how that helped because it simply doesnt matter

**Comment by GilesTNT** [comment]
Not entirely sure what you mean about misusing funds? Also goMINT buybacks were part of our lite paper and have always been about increasing protocol owned liquidity from revenue. It's a shame you guys have such a negative attitude.

**Comment by 2lobo** [comment]
> Not entirely sure what you mean about misusing funds? Also goMINT buybacks were part of our lite paper and have always been about increasing protocol owned liquidity from revenue. It's a shame you guys have such a negative attitude.

you are using funds of the defi boost which is supposed to go to users for development stuff and you are telling me that i am the problem here? 

i would have a better attitude towards all of it if you would start being transparent in advance instead of us having to explicitly ask and find out that you are using the funds in a way that they werent supposed to be used for. maybe your attitude about all of this is the problem

**Comment by GilesTNT** [comment]
@2lobo This marketing initiative was discussed at length in 2 defi-council meetings. It was approved to go ahead, as long as the community were the beneficiaries it fell within the language.  X-NFT has ONLY been distributed to the community in the same manner Algo would have as rewards, the return for the community is currently much greater than the Algo. If you believe we have misappropriated funds or moved without approval I can assure you we did not and we took every precaution to ensure the community were the beneficiaries. With regard to transparency I don't believe we have hidden anything here as I mentioned previously there was 8000A used for minting the NFT's (all of which will belong to X-NFT holders) the remainder would have been split between artist payment (supporting an Algorand artist) and contract (launching on and supporting Hone_fi mainnet) the total of which would not exceed 40,000A.  If you still have concerns please submit a ticket at Algomint.io, clearly outline your grievances I will make sure the team answer with enough information to hopefully satisfy you of our intent. We really are doing everything we can to be innovative and remain positive in this struggling ecosystem/market, we are certainly not in the habit of breaking rank.

**Comment by 2lobo** [comment]
> @2lobo This marketing initiative was discussed at length in 2 defi-council meetings. It was approved to go ahead, as long as the community were the beneficiaries it fell within the language. X-NFT has ONLY been distributed to the community in the same manner Algo would have as rewards, the return for the community is currently much greater than the Algo. If you believe we have misappropriated funds or moved without approval I can assure you we did not and we took every precaution to ensure the community were the beneficiaries. With regard to transparency I don't believe we have hidden anything here as I mentioned previously there was 8000A used for minting the NFT's (all of which will belong to X-NFT holders) the remainder would have been split between artist payment (supporting an Algorand artist) and contract (launching on and supporting Hone_fi mainnet) the total of which would not exceed 40,000A. If you still have concerns please submit a ticket at Algomint.io, clearly outline your grievances I will make sure the team answer with enough information to hopefully satisfy you of our intent. We really are doing everything we can to be innovative and remain positive in this struggling ecosystem/market, we are certainly not in the habit of breaking rank.

"....it feel withing the language" seems like T&C are a joke to everyone here, good to know. if this went through the defi council then they made a huge mistake here imho. but i mean the defi committee consists of dapp leaders that are reliant on each other and dont care to inform the community in advance so what do i expect. on top you clearly didnt state how the whole X-NFT was funded when you announced it, I had to ask you here how the funds were used in a thread that is about giving you even more funds of the defi boost. there are projects out there that request money through xGov grants and all you needed to do is to take funds of the defi boost and redirect them, you think thats fair?

**Comment by 2lobo** [comment]
and i wanna point out that i know how hard this market is for everyone but that's not the time to bend rules when you think its ok to. the community is here and all we want is start talking to us! if i could vote for dev funds instead of governance rewards i would happily do this

**Comment by ErikHasselwander** [comment]
The governance period 6 vote says the following:

> The goal is to give Defi projects more flexibility in how these rewards are structured and distributed among their user base, targeting rapid growth, deeper DEX liquidity, and incentives for users who come to Algorand in the middle of a governance period.

> Projects must provide transparency to the community about how the rewards were distributed at the end of each quarter and those that fail to distribute rewards directly to users will be ineligible for subsequent periods, until they’ve distributed all the rewards received under this program.

(https://governance.algorand.foundation/governance-period-6/period-6-voting-session-1)

You guys over at Algomint clearly didnt follow this, specifically: "those that fail to distribute rewards directly to users will be ineligible for subsequent periods". You did not distribute your rewards directly to users, you distributed them directly to your own developers. This is not what was voted for in governance, and it is not inside ARC48.md. Imo it doesn't matter if the "DeFi committee" decides something in private, no where in public does this program allow you to use funds in this manner, the 5% to marketing deal was a stretch to begin with, but this is just blatant abuse. You can justify it all you want, but in the end you have broken the terms that were voted for in governance, and you're not following the publicly available specs.(https://github.com/algorandfoundation/ARCs/blob/main/ARCs/arc-0048.md).

**Comment by GilesTNT** [comment]
@2lobo Absolutely not, if it were a joke to us we would not have spent the time assuring that our proposal fell within the guidelines. We will absolutely inform the community on our spend (as discussed previously). Again to reiterate the current spend is only 8000A for deployment. If I have led you to believe that the 5% marketing allocation has funded X-NFT development (5% for us is about $4000 usd) it just is not the case, if we used all the funds (which we obv have not, to reiterate only 8000A ~$800) it would only cover a small proportion of costs. For the record, I came here of my own volition and have been transparent. Personally I would rather all this was done publicly. During the discussions around the 5% marketing allocation I advocated for a "rapid response" option in governance where situations like this can be voted on by the community but wouldn't affect eligibility if the vote was missed. The reasoning behind this logic is we work in an incredibly dynamic field and sometimes the burden of bureaucracy is detrimental.

**Comment by GhostOfMcAfee** [comment]
> Therefore, I suggest to add a requirement to T&C of DeFi rewards that any giveaway must be verifiably random. 

I would be in favor of scrapping giveaways entirely. I am skeptical that they have any real ROI. But, to the extent they are permitted they absolutely need a requirement that they are verifiably random. 

Rewards should never be permitted to be used in any sort of manner where insiders can game the system to the detriment of the community. The only way to stop corrupt behavior is to design systems so that this (as much as possible) is not an option. If gamesmanship and insider graft is a possibility, it will happen given a long enough time frame. When that happens, it hurts faith not only in the particular protocol, but it also hurts faith in the Algo Foundation. 

This community has been beaten down for so long, we cannot afford more of these types of unforced errors.

**Comment by 2lobo** [comment]
> During the discussions around the 5% marketing allocation I advocated for a "rapid response" option in governance where situations like this can be voted on by the community but wouldn't affect eligibility if the vote was missed. The reasoning behind this logic is we work in an incredibly dynamic field and sometimes the burden of bureaucracy is detrimental.

yeah this whole 3 month thing is really annoying as its really slow. we cant really react in an appropriate amount of time to stuff. 

but i stand behind my comment that this was not ok and the funds were misused even if the defi committee approved them. the defi committee has clearly shown they can't follow the rules set approved by the community which is pretty sad

**Comment by GhostOfMcAfee** [comment]
> The reasoning behind this logic is we work in an incredibly dynamic field and sometimes the burden of bureaucracy is detrimental.

What one person characterizes as "bureaucracy," another characterizes as "rules designed to prevent self-dealing." 

The solution would have been to abide by the rules and publicly complain about how you think the rules need to change: "Hey, we would have really wanted to spend X amount on Y. We think it would have Z benefits. But the current rules wouldn't allow us. So, we would like to make ABC changes to the rules, and here is why we think this is fair and not subject to abuse." 

As @ErikHasselwander points out . . . 

>This is not what was voted for in governance, and it is not inside ARC48.md. Imo it doesn't matter if the "DeFi committee" decides something in private, no where in public does this program allow you to use funds in this manner

Rules are meaningless if not followed. And, it erodes trust overall when they are broken. So, while in the case of AlgoMint, the net amounts we are talking about may be small, and it might actually have been a good idea (if the rules permitted it), it was not okay. 

While I don't view this as being an issue of lack of honesty/integrity on AlgoMint's part, I do think this is another unforced error. _Perception and sentiment are important, and there are people out there who will not pass up an opportunity to paint Algorand and its community in a terrible light_ (anybody remember that recent coordinated Clinton Foundation attack?). This coupled with other recent events can absolutely be strung together to make a damning set of headlines.

"This week in Algorand DeFi . . . Who can you Trust?: One Algo DeFi Platform has secret meetings to monopolize consensus rewards; a second DeFi Platform uses funds meant for users to pay its team; a third DeFi platform awards its insider with a 50K Algo giveaway meant for users." 

I don't care if you think that headline is unfair, that is the sort of things that others will write. And it will be shared. And it will hurt us.

People in this community are sick and tired with what seems to be a lack of transparency. Seeing a call for less "bureaucracy" in favor of more "flexibility" is not going to go over well. And if these changes result in more questionable stuff, people will leave.

**Comment by GhostOfMcAfee** [comment]
> yeah this whole 3 month thing is really annoying as its really slow. we cant really react in an appropriate amount of time to stuff.

Agree. I personally believe Governance is non-functional because it tries to be too inclusive. We hand out rewards to people who don't care to educate themselves about the ecosystem and honestly don't care about anything more than reaping the rewards. If I had my druthers, Governance would be much shorter periods (along with xGov).

**Comment by GilesTNT** [comment]
@GhostOfMcAfee. Firstly I was saying governance can be smarter, faster and more dynamic I certainly didn't say there should be less, my feelings are there should be more and it should be fluid to enable processes like this to be viewed by the public (I am all for that). Crypto moves so fast (even in this dire market) that we all need to be agile, I don't like seeing rewards going round and round in our ecosystem and not generating any real growth or the desperately needed user acquisition. I am talking to the team today regarding the the accusations directed at us in this forum and will circle back with comments.

**Comment by GhostOfMcAfee** [comment]
@GilesTNT, I want to be abundantly clear that (as I said before) I do not think this is an issue of honesty/integrity on AlgoMint's part. If it was discussed and green-lighted as part of multiple DeFi Council meetings (as you have stated), then I view this as really being a problem of the DeFi Council generally thinking that they should be able to override the text of Governance votes. So, again, though I do think this violated the terms of the GP6 vote, I do not want to suggest that this was anything meant to be sneaky or fraudulent on AlgoMint's part. **However**, that bit of nuance is not the story that others will write and share and amplify on social media. And, they say "if you are explaining, you are losing." 

And, yes, I 100% agree with you on the need for a faster and more dynamic way of doing things (as I've said elsewhere). If I had a magic wand, Governance and xGovs would be radically different. It would be faster paced, require lots more work, and be much more dynamic. That, IMO is the solution. Make the system meet the demands of the space.

**Comment by borg-sauce** [comment]
> @2lobo This marketing initiative was discussed at length in 2 defi-council meetings. It was approved to go ahead, as long as the community were the beneficiaries it fell within the language. X-NFT has ONLY been distributed to the community in the same manner Algo would have as rewards, the return for the community is currently much greater than the Algo. If you believe we have misappropriated funds or moved without approval I can assure you we did not and we took every precaution to ensure the community were the beneficiaries. With regard to transparency I don't believe we have hidden anything here as I mentioned previously there was 8000A used for minting the NFT's (all of which will belong to X-NFT holders) the remainder would have been split between artist payment (supporting an Algorand artist) and contract (launching on and supporting Hone_fi mainnet) the total of which would not exceed 40,000A. If you still have concerns please submit a ticket at Algomint.io, clearly outline your grievances I will make sure the team answer with enough information to hopefully satisfy you of our intent. We really are doing everything we can to be innovative and remain positive in this struggling ecosystem/market, we are certainly not in the habit of breaking rank.

It cost you 8,000A to mint it??? That doesn't make sense at all it's practically free

**Comment by GilesTNT** [comment]
@borg-sauce 

The minting itself cost roughly 3 Algo. However, all 3,000 NFTs then needed to be opted into and transferred to the smart contract and, on deposit, recorded in a box storage list (think a long array of asset IDs). This is the expensive part, costing around 2 Algo per asset to call the opt-in method and the deposit methods, as a single transaction group.
Why is it so expensive? Each app call has a box read budget, which is the amount of box storage that can be read by that transaction. This maxes out pretty quickly, and to read the full 3000-long box list it required an additional 3 “dummy” application calls added to the transaction group, which are simply used so that we can add more box references to the transactions box array, thereby increasing the box read budget and allowing the transaction to write the NFT’s asset ID to the box list.
Below is an example of the cost of one transaction group for one NFT to be added to the contract:
image


In addition the NFT creator and the smart contract's app account must have a min balance that increases with each asset by .1 algo. So each account has to retain a balance of about 300 A, so that's another 600 A

**Comment by GilesTNT** [comment]
@GhostOfMcAfee @ErikHasselwander @2lobo 
So to be clear there has been 0 money from rewards spent on dev resources, the only spend as previously mentioned is the 8000A as detailed in my previous post which were the on chain costs (as in the actual ALGO costs for minting the NFT's, loading the HONE contracts etc), all dev time has been paid for by Algomint. Given the continuing concern around fund usage and the desire for upfront transparency Algomint are discussing the potential for a "pro-active" approach giving community a 1 week lead time on spends i.e giving notice to the community regarding up coming spends and leaving 1 week for replies. Also we will be engaging with the DeFi council and requesting a public facing document from meetings pertaining to reward spends.

**Comment by d13co** [comment]
> @borg-sauce
> In addition the NFT creator and the smart contract's app account must have a min balance that increases with each asset by .1 algo. So each account has to retain a balance of about 300 A, so that's another 600 A

Not sure why your app calls have such high fees set, though. This doesn't affect your opcode budget, or box budget. 

You need to set `.flatFee = true` and `.fee = 1000` in your app calls' suggestedParams. (If you have inner txns you need to add another 1000 microalgo per inner txn)

**Comment by defichamp** [comment]
@d13co Thanks I will pass this on

**Comment by defichamp** [comment]
> Given the continuing concern around fund usage and the desire for upfront transparency Algomint are discussing the potential for a "pro-active" approach giving community a 1 week lead time on spends i.e giving notice to the community regarding up coming spends and leaving 1 week for replies. Also we will be engaging with the DeFi council and requesting a public facing document from meetings pertaining to reward spends.

@GilesTNT thanks I will pass this on

**Comment by SudoWeezy** [comment]
PR Reopened here: https://github.com/algorandfoundation/ARCs/pull/247, please use the new thread.

**Pull request merged**
